# Generated by Django 3.1.2 on 2020-10-11 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baker',
            fields=[
                ('businessID', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='사업자 등록번호')),
                ('email', models.EmailField(max_length=128, null=True, unique=True, verbose_name='사업자 이메일')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='사업자 이름')),
                ('phoneNum', models.CharField(max_length=30, null=True, unique=True, verbose_name='사업자 전화번호')),
                ('password', models.CharField(max_length=30, null=True, verbose_name='사업자 비밀번호')),
            ],
        ),
        migrations.CreateModel(
            name='Orderer',
            fields=[
                ('email', models.EmailField(max_length=128, primary_key=True, serialize=False, verbose_name='주문자 이메일')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='주문자 이름')),
                ('phoneNum', models.CharField(max_length=30, null=True, unique=True, verbose_name='주문자 전화번호')),
                ('password', models.CharField(max_length=30, null=True, verbose_name='주문자 비밀번호')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('businessID', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='사업자 등록번호')),
                ('storeName', models.CharField(max_length=30, null=True, verbose_name='가게 이름')),
                ('location', models.CharField(max_length=200, null=True, verbose_name='가게 위치')),
                ('storeContact', models.CharField(max_length=30, null=True, unique=True, verbose_name='가게 연락처')),
                ('storeOpen', models.CharField(choices=[('14:00', '14:00'), ('22:30', '22:30'), ('18:30', '18:30'), ('9:00', '9:00'), ('10:00', '10:00'), ('11:30', '11:30'), ('17:00', '17:00'), ('13:30', '13:30'), ('12:00', '12:00'), ('13:00', '13:00'), ('10:30', '10:30'), ('15:00', '15:00'), ('20:00', '20:00'), ('19:30', '19:30'), ('12:30', '12:30'), ('16:30', '16:30'), ('18:00', '18:00'), ('22:00', '22:00'), ('16:00', '16:00'), ('20:30', '20:30'), ('17:30', '17:30'), ('21:30', '21:30'), ('15:30', '15:30'), ('11:00', '11:00'), ('14:30', '14:30'), ('19:00', '19:00'), ('21:00', '21:00'), ('9:30', '9:30')], max_length=15, null=True, verbose_name='가게 오픈 시간')),
                ('storeClose', models.CharField(choices=[('14:00', '14:00'), ('22:30', '22:30'), ('18:30', '18:30'), ('9:00', '9:00'), ('10:00', '10:00'), ('11:30', '11:30'), ('17:00', '17:00'), ('13:30', '13:30'), ('12:00', '12:00'), ('13:00', '13:00'), ('10:30', '10:30'), ('15:00', '15:00'), ('20:00', '20:00'), ('19:30', '19:30'), ('12:30', '12:30'), ('16:30', '16:30'), ('18:00', '18:00'), ('22:00', '22:00'), ('16:00', '16:00'), ('20:30', '20:30'), ('17:30', '17:30'), ('21:30', '21:30'), ('15:30', '15:30'), ('11:00', '11:00'), ('14:30', '14:30'), ('19:00', '19:00'), ('21:00', '21:00'), ('9:30', '9:30')], max_length=15, null=True, verbose_name='가게 마감 시간')),
                ('pickUpOpen', models.CharField(choices=[('14:00', '14:00'), ('22:30', '22:30'), ('18:30', '18:30'), ('9:00', '9:00'), ('10:00', '10:00'), ('11:30', '11:30'), ('17:00', '17:00'), ('13:30', '13:30'), ('12:00', '12:00'), ('13:00', '13:00'), ('10:30', '10:30'), ('15:00', '15:00'), ('20:00', '20:00'), ('19:30', '19:30'), ('12:30', '12:30'), ('16:30', '16:30'), ('18:00', '18:00'), ('22:00', '22:00'), ('16:00', '16:00'), ('20:30', '20:30'), ('17:30', '17:30'), ('21:30', '21:30'), ('15:30', '15:30'), ('11:00', '11:00'), ('14:30', '14:30'), ('19:00', '19:00'), ('21:00', '21:00'), ('9:30', '9:30')], max_length=15, null=True, verbose_name='픽업 오픈 시간')),
                ('pickUpClose', models.CharField(choices=[('14:00', '14:00'), ('22:30', '22:30'), ('18:30', '18:30'), ('9:00', '9:00'), ('10:00', '10:00'), ('11:30', '11:30'), ('17:00', '17:00'), ('13:30', '13:30'), ('12:00', '12:00'), ('13:00', '13:00'), ('10:30', '10:30'), ('15:00', '15:00'), ('20:00', '20:00'), ('19:30', '19:30'), ('12:30', '12:30'), ('16:30', '16:30'), ('18:00', '18:00'), ('22:00', '22:00'), ('16:00', '16:00'), ('20:30', '20:30'), ('17:30', '17:30'), ('21:30', '21:30'), ('15:30', '15:30'), ('11:00', '11:00'), ('14:30', '14:30'), ('19:00', '19:00'), ('21:00', '21:00'), ('9:30', '9:30')], max_length=15, null=True, verbose_name='픽업 마감 시간')),
                ('aboutStore', models.TextField(blank=True, null=True, verbose_name='가게 소개글')),
                ('storeImg', models.ImageField(blank=True, null=True, upload_to='', verbose_name='가게 대표이미지')),
                ('monday', models.IntegerField(default=0, verbose_name='월요일 주문가능 수량')),
                ('tuesday', models.IntegerField(default=0, verbose_name='화요일 주문가능 수량')),
                ('wednesday', models.IntegerField(default=0, verbose_name='수요일 주문가능 수량')),
                ('thursday', models.IntegerField(default=0, verbose_name='목요일 주문가능 수량')),
                ('friday', models.IntegerField(default=0, verbose_name='금요일 주문가능 수량')),
                ('saturday', models.IntegerField(default=0, verbose_name='토요일 주문가능 수량')),
                ('sunday', models.IntegerField(default=0, verbose_name='일요일 주문가능 수량')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thecakeapp.baker')),
            ],
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('store_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='thecakeapp.store')),
                ('cakeName', models.CharField(max_length=200, null=True, unique=True, verbose_name='케이크 이름')),
                ('cakeImg', models.ImageField(null=True, upload_to='', verbose_name='케이크 이미지')),
                ('cakePrice', models.IntegerField(null=True, verbose_name='1호 기준 가격')),
                ('mini', models.BooleanField(default=False, null=True, verbose_name='미니사이즈 가능 여부')),
            ],
            bases=('thecakeapp.store',),
        ),
        migrations.CreateModel(
            name='DetailedOption',
            fields=[
                ('store_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='thecakeapp.store')),
                ('optionName', models.CharField(max_length=30, null=True, verbose_name='옵션명')),
                ('isNecessary', models.BooleanField(default=False, null=True, verbose_name='필수 여부')),
                ('detailName', models.CharField(max_length=50, null=True, verbose_name='옵션 세부항목명')),
                ('pricing', models.IntegerField(null=True, verbose_name='추가 금액')),
                ('withColor', models.BooleanField(default=False, null=True, verbose_name='색상판 유무')),
                ('withImage', models.BooleanField(default=False, null=True, verbose_name='이미지추가 유무')),
            ],
            options={
                'abstract': False,
            },
            bases=('thecakeapp.store',),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('orderNum', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='주문 번호')),
                ('taste', models.IntegerField(null=True, verbose_name='맛 평점')),
                ('service', models.IntegerField(null=True, verbose_name='서비스 평점')),
                ('design', models.IntegerField(null=True, verbose_name='디자인 평점')),
                ('textReview', models.TextField(blank=True, null=True, verbose_name='한 줄 후기')),
                ('cakeStore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thecakeapp.store')),
                ('orderer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thecakeapp.orderer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderNum', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False, verbose_name='주문 번호')),
                ('pickupDate', models.CharField(max_length=30, null=True, verbose_name='희망 수령일')),
                ('pickupTime', models.CharField(max_length=20, null=True, verbose_name='희망 픽업 시간')),
                ('businessID', models.CharField(max_length=50, null=True, verbose_name='사업자 등록번호')),
                ('cakeName', models.CharField(max_length=200, null=True, verbose_name='케이크 이름')),
                ('requiredOpt', models.TextField(null=True, verbose_name='필수 선택 옵션')),
                ('additionalOpt', models.TextField(blank=True, null=True, verbose_name='추가 선택 옵션')),
                ('cakeText', models.TextField(blank=True, null=True, verbose_name='케이크 문구')),
                ('message', models.TextField(blank=True, null=True, verbose_name='요청 사항')),
                ('price', models.IntegerField(null=True, verbose_name='가격')),
                ('status', models.CharField(max_length=30, null=True, verbose_name='주문 진행 상황')),
                ('orderer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thecakeapp.orderer')),
            ],
        ),
    ]
